"""赢币 + 账单：持久化存储（Phase-2）。

双后端，公共 API 不变：
- 设置 DATABASE_URL → Postgres（psycopg3），生产持久 + 跨实例一致。
- 否则 → 本地 SQLite（data/app.db），本地开发零依赖。

并发正确性：扣费/建户/每日赠币均为原子条件写（RETURNING / ON CONFLICT），
不超扣、不透支、不重复发币。SQLite 3.35+ 与 Postgres 语法一致，仅建表 DDL 分叉。
"""

import os
import sqlite3
import uuid
from contextlib import contextmanager
from datetime import date, datetime, timedelta
from pathlib import Path

DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
IS_PG = bool(DATABASE_URL)

# 本地 SQLite 路径（仅未配置 DATABASE_URL 时使用）。
if os.environ.get("YD_DB"):
    DB_PATH = Path(os.environ["YD_DB"])
elif os.environ.get("VERCEL"):
    DB_PATH = Path("/tmp/yd_app.db")   # 兜底：未接 PG 时仍可跑（数据临时）
else:
    DB_PATH = Path(__file__).parent.parent / "data" / "app.db"

NEW_USER_COINS = 10   # 新用户赠送
DAILY_COINS = 3       # 每日登录赠送
COST_PER_GEN = 1      # 每次完整研判消耗

PLANS = {
    "pack50": {"name": "9.9元 / 50赢币", "coins": 50, "price": 9.9},
    "monthly": {"name": "19.9元 / 月度无限赢币", "coins": 0, "price": 19.9, "days": 30},
}


def _q(sql: str) -> str:
    """占位符适配：SQL 一律用 ?，Postgres 下转成 %s。"""
    return sql.replace("?", "%s") if IS_PG else sql


@contextmanager
def _conn():
    """开连接 → 成功提交 / 异常回滚 → 关闭。两后端接口统一走 cursor。"""
    if IS_PG:
        import psycopg
        from psycopg.rows import dict_row
        conn = psycopg.connect(DATABASE_URL, row_factory=dict_row)
    else:
        DB_PATH.parent.mkdir(parents=True, exist_ok=True)
        conn = sqlite3.connect(DB_PATH)
        conn.row_factory = sqlite3.Row
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def _now() -> str:
    return datetime.now().isoformat(timespec="seconds")


def init_db():
    # 自增主键 DDL 是两库唯一的语法差异。
    ledger_id = ("id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
                 if IS_PG else "id INTEGER PRIMARY KEY AUTOINCREMENT")
    with _conn() as c:
        cur = c.cursor()
        cur.execute("""CREATE TABLE IF NOT EXISTS users (
            id TEXT PRIMARY KEY,
            coins INTEGER NOT NULL,
            member_until TEXT,
            last_daily TEXT,
            created_at TEXT NOT NULL
        )""")
        cur.execute(f"""CREATE TABLE IF NOT EXISTS ledger (
            {ledger_id},
            user_id TEXT NOT NULL,
            delta INTEGER NOT NULL,
            reason TEXT NOT NULL,
            ts TEXT NOT NULL
        )""")


def _log(cur, user_id: str, delta: int, reason: str):
    cur.execute(_q("INSERT INTO ledger (user_id, delta, reason, ts) VALUES (?,?,?,?)"),
                (user_id, delta, reason, _now()))


def _fetch_user(cur, user_id: str) -> dict | None:
    cur.execute(_q("SELECT * FROM users WHERE id=?"), (user_id,))
    row = cur.fetchone()
    return dict(row) if row else None


def get_or_create_user(user_id: str | None) -> dict:
    """取用户；不存在则原子建户并发新人赢币；每天首访原子发每日赢币。"""
    today = date.today().isoformat()
    with _conn() as c:
        cur = c.cursor()

        if not user_id:
            user_id = uuid.uuid4().hex

        # 原子建户：并发下只有真正插入的那次会拿到 RETURNING 行，避免重复发币。
        cur.execute(
            _q("""INSERT INTO users (id, coins, last_daily, created_at)
                  VALUES (?,?,?,?) ON CONFLICT (id) DO NOTHING RETURNING id"""),
            (user_id, NEW_USER_COINS, today, _now()))
        if cur.fetchone() is not None:
            _log(cur, user_id, NEW_USER_COINS, "新用户赠送")
            return _fetch_user(cur, user_id)

        # 已存在：原子发放每日赠币（仅当今天还没发过）。
        cur.execute(
            _q("""UPDATE users SET coins = coins + ?, last_daily = ?
                  WHERE id = ? AND (last_daily IS NULL OR last_daily <> ?)
                  RETURNING coins"""),
            (DAILY_COINS, today, user_id, today))
        if cur.fetchone() is not None:
            _log(cur, user_id, DAILY_COINS, "每日登录赠送")

        return _fetch_user(cur, user_id)


def is_member(user: dict) -> bool:
    mu = user.get("member_until")
    return bool(mu) and mu >= date.today().isoformat()


def try_spend(user_id: str) -> tuple[bool, dict]:
    """原子扣一次生成费。会员不扣。返回 (是否成功, 最新用户)。"""
    with _conn() as c:
        cur = c.cursor()
        user = _fetch_user(cur, user_id)
        if user is None:
            return False, {}
        if is_member(user):
            return True, user

        # 条件扣费：余额足才扣，天然防透支与并发超扣。
        cur.execute(
            _q("UPDATE users SET coins = coins - ? WHERE id = ? AND coins >= ? RETURNING coins"),
            (COST_PER_GEN, user_id, COST_PER_GEN))
        row = cur.fetchone()
        if row is None:
            return False, user   # 余额不足
        _log(cur, user_id, -COST_PER_GEN, "赢面研判消耗")
        user["coins"] = dict(row)["coins"]
        return True, user


def refund(user_id: str):
    """生成失败时退回赢币（仅在扣费成功且非会员时调用）。"""
    with _conn() as c:
        cur = c.cursor()
        cur.execute(_q("UPDATE users SET coins = coins + ? WHERE id = ?"),
                    (COST_PER_GEN, user_id))
        _log(cur, user_id, COST_PER_GEN, "生成失败退回")


def recharge(user_id: str, plan_id: str) -> dict:
    """Phase-2 仍为 mock 充值，不接支付，直接到账并记账（数据已持久）。"""
    plan = PLANS[plan_id]
    with _conn() as c:
        cur = c.cursor()
        if plan_id == "monthly":
            user = _fetch_user(cur, user_id)
            base = date.today()
            mu = user.get("member_until") if user else None
            if mu and mu >= base.isoformat():
                base = date.fromisoformat(mu)
            until = (base + timedelta(days=plan["days"])).isoformat()
            cur.execute(_q("UPDATE users SET member_until=? WHERE id=?"), (until, user_id))
            _log(cur, user_id, 0, f"充值[mock]：{plan['name']}")
        else:
            cur.execute(_q("UPDATE users SET coins = coins + ? WHERE id = ?"),
                        (plan["coins"], user_id))
            _log(cur, user_id, plan["coins"], f"充值[mock]：{plan['name']}")
        return _fetch_user(cur, user_id)


def billing(user_id: str, limit: int = 50) -> list[dict]:
    with _conn() as c:
        cur = c.cursor()
        cur.execute(
            _q("SELECT delta, reason, ts FROM ledger WHERE user_id=? ORDER BY id DESC LIMIT ?"),
            (user_id, limit))
        return [dict(r) for r in cur.fetchall()]
